## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [15]:
import numpy as np
num_arr_1 = np.arange(10,41)
num_arr_2 = np.arange(220,251)
num_arr_3 = num_arr_1 + num_arr_2
num_arr_3


array([230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290])

2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [16]:
arr = np.arange(100, 100+10*7)
matrix = arr.reshape((10,7))
matrix

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [39]:
arr_1 = np.arange(1, 101)
arr_2 = np.arange(1, 101)
arr_1 = np.where(arr_1 % 2 == 0)
arr_2 = np.where(arr_2 % 2 == 1)

result = np.multiply(arr_1, arr_2)

result


array([[   0,    6,   20,   42,   72,  110,  156,  210,  272,  342,  420,
         506,  600,  702,  812,  930, 1056, 1190, 1332, 1482, 1640, 1806,
        1980, 2162, 2352, 2550, 2756, 2970, 3192, 3422, 3660, 3906, 4160,
        4422, 4692, 4970, 5256, 5550, 5852, 6162, 6480, 6806, 7140, 7482,
        7832, 8190, 8556, 8930, 9312, 9702]], dtype=int64)

4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [54]:
arr = np.random.randint(1,1001, size=(40,5))
result = arr[(arr % 2 == 0) & (arr % 5 == 0)]
result


array([190, 470, 620, 320, 220, 780, 610, 830, 280, 560, 990, 140, 700,
       750, 900, 390,  40,  10, 520,  20, 930, 270])